version: '3'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    container_name: servicio_mysql_76591779
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: "nextcloud:21.0.0-apache"
    restart: always
    container_name: servicio_nextcloud_76591779
    expose:
      - "80"
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - .env
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: servicio_nginx_76591779
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud
    ports:
      - "31006:80"

  ldap:
    image: larrycai/openldap
    container_name: servicio_ldap_76591779
    depends_on:
      - nextcloud